### ISSUE TITLE
Not able to enable plugins for device

### ISSUE THREAD

**Issue by chrissi-p** [andyholmes/gnome-shell-extension-gsconnect#34]
Most parts of GSConnect seem to work fine. I am able to connect my phone and so on.
But if I click on the indicator of my phone it says **no plugins enabled** an if I try to enable them, the settings get lost. If I open the plugin settings again they are all disabled again.

The Daemon log prints the following:
```
JS ERROR: TypeError: this.device.disablePlugin is not a function
PluginControl<._toggle@/home/chrissi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:137:17
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/chrissi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:889:2

JS ERROR: TypeError: this.device.enablePlugin is not a function
PluginControl<._toggle@/home/chrissi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/widgets/device.js:118:26
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
@/home/chrissi/.local/share/gnome-shell/extensions/gsconnect@andyholmes.github.io/service/daemon.js:889:2

g_object_unref: assertion 'G_IS_OBJECT (object)' failed
```

I use Antergos with Gnome Shell 26.2
The plugins looks very promising and I hope you can help with the problem. 
Thanks 👍

**Comment by andyholmes** [comment]
I can't seem to reproduce this, what version of GSConnect are your using and how did you get it?

**Comment by vredesbyyrd** [comment]
I am also having the same issue when i updated from version 8 to 9. Everything appears to be communicating correctly, but it says 'no plugins loaded'. I can ping etc. successfully. I uninstalled, deleted all keys from gsettings and rebuilt, thinking maybe there was something conflicting between version updates. No go. Rolled back to version 8 at and issue is gone.  

Any info you need just let me know.

**Comment by andyholmes** [comment]
Very little changed with the plugins between v8 and v9, nothing I see that should affect this. Did you try restarting Gnome Shell to ensure the extension was reloaded?

**Comment by vredesbyyrd** [comment]
I did. I also tried reinstalling the kde-connect app on android. And i scrubbed every trace of gsconnect from my computer and rebuilt it. Nothing seemed to make a difference.. Went back to v8 and everything is fine. I may try to take a closer look when i have time, but cant think of anything else really.

**Comment by chrissi-p** [comment]
I also use v9. I'm new to GSConnect so never tried v8.
I used the installation instructions in the wiki ([Building from Git](https://github.com/andyholmes/gnome-shell-extension-gsconnect/wiki/Installation#building-from-git))
All the dependencies should be installed.

**Comment by andyholmes** [comment]
If you're building from Git then your getting the "unstable" version, basically what I'm working on right now. The v9 on the releases page should work though. @vredesbyyrd are you also building from Git?

**Comment by vredesbyyrd** [comment]
Yes i have been building from git. I should have thought of that. I will build from the releases page later tonight. 

Thanks.

**Comment by chrissi-p** [comment]
Oh you are right, makes sense.
Now I used the v9 from the release page and it works also :)

Thank you very much for the support and the awesome extension 👍
